### ISSUE TITLE
Bad date field causes data to fail generating

### ISSUE THREAD

**Issue by johnbeech** [connected-web/boardgames-api#72]
Scenario - Hannah created a partial entry in the google sheet which was missing the the date field - subsequently, this generated an uncaught error which prevented the rest of the data being generated - this resulted in old data being uploaded.

```
(node:1669) UnhandledPromiseRejectionWarning: RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at convertGSheetsDate (/home/runner/work/boardgames-api/boardgames-api/src/util/convertGSheetsDate.js:3:15)
    at /home/runner/work/boardgames-api/boardgames-api/src/processors/boardgameIndex.js:45:19
    at Array.forEach (<anonymous>)
    at mapCaliPlayStatGame (/home/runner/work/boardgames-api/boardgames-api/src/processors/boardgameIndex.js:42:26)
    at Array.reduce (<anonymous>)
    at createIndex (/home/runner/work/boardgames-api/boardgames-api/src/processors/boardgameIndex.js:20:17)
    at /home/runner/work/boardgames-api/boardgames-api/src/processors/boardgameIndex.js:123:16
    at Object.start [as create-boardgame-index] (/home/runner/work/boardgames-api/boardgames-api/scripts/create-boardgame-index.js:16:27)
    at async processScripts (/home/runner/work/boardgames-api/boardgames-api/run.js:68:24)
(node:1669) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1669) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by johnbeech** [comment]
Closing; not causing an issue at present.
